language: node_js
node_js:
- '0.11'
- '0.10'
services:
- couchdb
install:
- python createviews.py
before_script:
- npm install
- npm install -g se-interpreter
script:
- se-interpreter interpreter_config.json
env:
  global:
  - SAUCE_USERNAME=ber_ola
  - SAUCE_ACCESS_KEY=b8931678-3c34-43a1-9a91-7830b62bbe23
