language: node_js
node_js:
- '0.11'
- '0.10'
services:
- couchdb
install:
- python createviews.py
before_script:
- npm install
- npm install -g se-interpreter
script:
- se-interpreter interpreter_config.json
env:
  global:
  - SAUCE_USERNAME=ber_ola
  - secure: jsMxUzcU0BM8lmD822gLgHt/jndGxpev3uIrL84IGl4WUHv3bTVpfmcT+CQqwylHwffbEE+X6zJ5M1L1sIorwBPR6m5Ij6Vo7J3QtzPkMXe+ePpioyd4XgcK0TNtSDFmLGifpe9Sh9E64qh4dzMrcgdAEi2C821Ck91I7xhMfk0=
deploy:
  provider: cloudcontrol
  email: contact@moehlenhof.net
  password:
    secure: PWcB1+lJ2uZxmbq4YPurfjiYLbV93efuD4lDt/nQh3Q+VazHsk0u6u8sG3mLiCqlQEaoxKOdbGPpWJ2u3iAu+RKqP/NQ4pYl5NfcvaA9ZGQW3Ex5jDbyy53m++DDHo6ue7Cb+m7e6TPQ8I7SUUXiBO+mVplX3qI1qGdhU6leZ8Y=
  deployment: tmc/default
